"""empty message

Revision ID: cc94a4bdab70
Revises: 2ed351921eb2
Create Date: 2022-02-09 22:31:14.073579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc94a4bdab70'
down_revision = '2ed351921eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'result')
    op.add_column('votes', sa.Column('user_jmbg', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'user_jmbg')
    op.add_column('participants', sa.Column('result', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
